name: Deploy to WP Engine
on:
  push:
    branches:
      - Prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run build --if-present
      - name: Clean up
        run: rm -rf node_modules
      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: 'cyberbreach'
          # Deploy Options
          REMOTE_PATH: 'wp-content/themes/cyberbreach/'
          FLAGS: -azvr --inplace --delete --exclude='.git'
